# Generated by Django 6.0.2 on 2026-08-26 17:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_academique', models.CharField(default='2025-2026', max_length=20)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='accounts.enseignant')),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='academic.ue')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'unique_together': {('ue', 'annee_academique')},
            },
        ),
        migrations.CreateModel(
            name='InscriptionUE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_academique', models.CharField(default='2025-2026', max_length=20)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='accounts.etudiant')),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_etudiants', to='academic.ue')),
            ],
            options={
                'verbose_name': 'Inscription à une UE',
                'verbose_name_plural': 'Inscriptions aux UE',
                'unique_together': {('etudiant', 'ue', 'annee_academique')},
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_evaluation', models.CharField(choices=[('CC', 'Contrôle Continu'), ('TP', 'Travaux Pratiques'), ('SN', 'Session Normale'), ('RAT', 'Rattrapage')], max_length=3)),
                ('valeur_note', models.DecimalField(blank=True, decimal_places=2, help_text='Note comprise entre 0 et 20', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(20.0)])),
                ('est_publie', models.BooleanField(default=False, verbose_name="Rendre visible à l'étudiant")),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='accounts.etudiant')),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='academic.ue')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'unique_together': {('etudiant', 'ue', 'type_evaluation')},
            },
        ),
    ]
