# Generated by Django 6.0.2 on 2026-08-28 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_departement_faculte_alter_filiere_code_filiere_and_more'),
        ('accounts', '0005_admincellule'),
        ('pedagogy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_academique', models.CharField(default='2025-2026', max_length=20)),
                ('etat', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ENVOYE', 'Envoyé à la cellule'), ('REJETE', 'Rejeté'), ('PUBLIE', 'Publié')], default='BROUILLON', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('commentaire_rejet', models.TextField(blank=True)),
                ('admin_traitement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pvs_traites', to='accounts.admincellule')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pvs', to='accounts.enseignant')),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pvs', to='academic.ue')),
            ],
            options={
                'verbose_name': 'Procès-verbal',
                'verbose_name_plural': 'Procès-verbaux',
                'ordering': ('-date_envoi', '-date_creation'),
            },
        ),
        migrations.CreateModel(
            name='PVNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('tp', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('sn', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_pv', to='accounts.etudiant')),
                ('pv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='pedagogy.pv')),
            ],
            options={
                'verbose_name': 'Ligne de PV',
                'verbose_name_plural': 'Lignes de PV',
            },
        ),
        migrations.AddConstraint(
            model_name='pv',
            constraint=models.UniqueConstraint(fields=('ue', 'annee_academique'), name='unique_pv_ue_annee'),
        ),
        migrations.AddConstraint(
            model_name='pvnote',
            constraint=models.UniqueConstraint(fields=('pv', 'etudiant'), name='unique_pv_etudiant'),
        ),
    ]
