# Generated by Django 6.0.2 on 2026-08-28 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_departement_faculte_alter_filiere_code_filiere_and_more'),
        ('accounts', '0005_admincellule'),
        ('pedagogy', '0002_pv_pvnote_pv_unique_pv_ue_annee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_evaluation', models.CharField(choices=[('CC', 'Contrôle Continu'), ('TP', 'Travaux Pratiques'), ('SN', 'Session Normale'), ('RAT', 'Rattrapage')], max_length=3)),
                ('motif', models.CharField(choices=[('ABSENCE', 'Absence de note'), ('NON_MERITEE', 'Note non méritée'), ('ERREUR', 'Erreur de note')], max_length=20)),
                ('description', models.TextField()),
                ('etat', models.CharField(choices=[('ENVOYEE', 'Envoyée'), ('VALIDEE', 'Validée')], default='ENVOYEE', max_length=10)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requetes_recues', to='accounts.enseignant')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requetes', to='accounts.etudiant')),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requetes', to='academic.ue')),
            ],
            options={
                'verbose_name': 'Requête étudiant',
                'verbose_name_plural': 'Requêtes étudiants',
                'ordering': ('-date_envoi',),
                'constraints': [models.UniqueConstraint(fields=('etudiant', 'ue', 'type_evaluation'), name='unique_requete_note_etudiant')],
            },
        ),
    ]
