# Generated by Django 6.0.2 on 2026-08-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_enseignant_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseignant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='user',
        ),
        migrations.AddField(
            model_name='enseignant',
            name='mot_de_passe',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='mot_de_passe',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
