# Generated by Django 6.0.2 on 2026-08-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnseignantUE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_declaration', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Habilitation Enseignant / UE',
                'verbose_name_plural': 'Habilitations Enseignants / UE',
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_filiere', models.CharField(help_text='Ex: INFO, MATH, BIO', max_length=20, unique=True)),
                ('nom_filiere', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Filière',
                'verbose_name_plural': 'Filières',
            },
        ),
        migrations.CreateModel(
            name='UE',
            fields=[
                ('code_ue', models.CharField(help_text='Ex: INF112', max_length=20, primary_key=True, serialize=False)),
                ('intitule', models.CharField(max_length=150)),
                ('credits', models.PositiveIntegerField()),
                ('avec_tp', models.BooleanField(default=False, verbose_name='Comporte des TP')),
                ('niveau', models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2')], max_length=2)),
                ('semestre', models.CharField(choices=[('S1', 'Semestre 1'), ('S2', 'Semestre 2')], max_length=2)),
            ],
            options={
                'verbose_name': "Unité d'Enseignement (UE)",
                'verbose_name_plural': "Unités d'Enseignement (UE)",
            },
        ),
    ]
