# Generated by Django 6.0.2 on 2026-08-26 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignantue',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations_ue', to='accounts.enseignant'),
        ),
        migrations.AddField(
            model_name='ue',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ues', to='academic.filiere'),
        ),
        migrations.AddField(
            model_name='enseignantue',
            name='ue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseignants_habilites', to='academic.ue'),
        ),
        migrations.AlterUniqueTogether(
            name='enseignantue',
            unique_together={('enseignant', 'ue')},
        ),
    ]
