# Generated by Django 6.0.2 on 2026-08-26 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_dept', models.CharField(help_text='Ex: INFO, MATH, PHYS', max_length=20, unique=True)),
                ('nom_dept', models.CharField(help_text="Ex: Département d'Informatique", max_length=150)),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
            },
        ),
        migrations.CreateModel(
            name='Faculte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_fac', models.CharField(help_text='Ex: FS, FALSH, FSEG', max_length=20, unique=True)),
                ('nom_fac', models.CharField(help_text='Ex: Faculté des Sciences', max_length=150)),
            ],
            options={
                'verbose_name': 'Faculté / Établissement',
                'verbose_name_plural': 'Facultés / Établissements',
            },
        ),
        migrations.AlterField(
            model_name='filiere',
            name='code_filiere',
            field=models.CharField(help_text='Ex: ICT4D, INFO_LMD', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='filiere',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filieres', to='academic.departement'),
        ),
        migrations.AddField(
            model_name='departement',
            name='faculte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departements', to='academic.faculte'),
        ),
    ]
