# Generated by Django 6.0.2 on 2026-08-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_departement_faculte_alter_filiere_code_filiere_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ue',
            name='pourcentage_cc',
            field=models.PositiveIntegerField(default=30, help_text='Pourcentage Contrôle Continu (0-100)'),
        ),
        migrations.AddField(
            model_name='ue',
            name='pourcentage_sn',
            field=models.PositiveIntegerField(default=50, help_text='Pourcentage Session Normale (0-100)'),
        ),
        migrations.AddField(
            model_name='ue',
            name='pourcentage_tp',
            field=models.PositiveIntegerField(default=20, help_text='Pourcentage Travaux Pratiques (0-100)'),
        ),
    ]
