# Generated by Django 6.0.2 on 2026-08-29 14:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_ue_pourcentage_cc_ue_pourcentage_sn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ue',
            name='pourcentage_cc',
            field=models.PositiveIntegerField(default=30, help_text='Pourcentage Contrôle Continu (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='ue',
            name='pourcentage_sn',
            field=models.PositiveIntegerField(default=50, help_text='Pourcentage Session Normale (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='ue',
            name='pourcentage_tp',
            field=models.PositiveIntegerField(default=20, help_text='Pourcentage Travaux Pratiques (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
